### PR TITLE
added fatal and gcd functions

### PR DESCRIPTION
**Pull request by icedragon789**
I found it would be advantageous for your tools module to contain a fatal function, where you can gracefully exit a program AND return an error message, all in one line. You're welcome.

### CODE REVIEW

**Review by bgree825 — CHANGES_REQUESTED** [review]
I agree, some of these additions could be beneficial. However, I cannot see the need to include a gcd function in this script. Please remove this or feel free to convince me otherwise.

**Comment by icedragon789** [comment]
Check out my new additions. I am sure you will enjoy what they have to offer to your already-robust program.

**Review by bgree825 — APPROVED** [review]
This looks great. Thank you for your hard work! See you at the Christmas party!

**Comment by bgree825** [comment]
Fantastic work Benjamin.

**Pull request merged**
